### ISSUE TITLE
Netlify build fails when package is installed with yarn

### ISSUE THREAD

**Issue by brinkofblink** [DreaMinder/nuxt-netlify-cache#1]
Firstly, thanks for building this. It's really useful and brought a recent project's deploy time from 6m58s to 4m40

I did have some issues when I installed the package using yarn though.
The Netlify build failed with the error `/usr/bin/env: ‘node\r’: No such file or directory`

It looks like this is to do with the line endings in your lib being CRLF rather than LF which breaks things in unix environments. Npm apparently corrects this automatically for installed modules but yarn does not (see https://github.com/yarnpkg/yarn/issues/5480).

**Comment by DreaMinder** [comment]
Thank you for the report! I've pushed a new version 1.0.2 with fixed line endings. Please let me know if it helped.
But keep in mind that 1.x.x  only works with latest Nuxt version (`nuxt export` instead of `nuxt generate`).

**Comment by brinkofblink** [comment]
Yep that worked. Thanks for fixing it so quickly.
Really enjoying the new `nuxt export` and this makes it even better.
