### ISSUE TITLE
[Question] How to change cacheFlag in advanced usage?

### ISSUE THREAD

**Issue by mornir** [DreaMinder/nuxt-netlify-cache#3]
Hi! It's me again 😁

I call all my build hooks "Sanity Studio Plugin Netlify Widget" in the Netlify dashboard:
![image](https://user-images.githubusercontent.com/1411843/86126565-d2c73c80-bade-11ea-8f19-d3e3bba4d28f.png)

So if I set the cacheFlag to "Sanity", this module should work without using the trigger_title query parameter?

My understanding is that [trigger_title](https://docs.netlify.com/configure-builds/build-hooks/#parameters) overrides the default [INCOMING_HOOK_TITLE](https://docs.netlify.com/configure-builds/environment-variables/#build-hook-metadata-and-payload) set in the dashboard when creating the hook.

**Comment by DreaMinder** [comment]
> So if I set the cacheFlag to "Sanity", this module should work without using the trigger_title query parameter?

In module usage - yes, you are right, it will work. But currently, there is no way to override cacheFlag in Advanced usage. 
I wanted to make env var that would change use_cache to something else, but decided to leave it for later. A command argument would be even better though: 
```
"scripts": {
  "generate:cached": "nuxt-netlify-cache --flag Sanity",
```

But I don't have time to implement it right now, maybe on the weekends.

**Comment by mornir** [comment]
Yes, passing the value as a command argument would be great 😀
No hurry, using the `trigger_title` query parameter works fine.

**Comment by mornir** [comment]
Considering how long it took for Nuxt to release its fully static mode, I thought it would took longer for that feature to be natively supported by Nuxt: https://nuxtjs.org/blog/nuxt-static-improvements
Looking forward to Nuxt v3 now! 😃
