### ISSUE TITLE
cached build & PWA / Service Worker

### ISSUE THREAD

**Issue by lukas-a-brand** [DreaMinder/nuxt-netlify-cache#5]
I found your package really useful and capped the rebuild time on Netlify by around 1/4 with it. 
But sadly the sw.js of the nuxt PWA module didnt work anymore and therefore all PWA functionality was lost.
Sadly I cannot use it without being able to ensure that the PWA still works out. :)

**Comment by DreaMinder** [comment]
@bstrdChronicles Aww... Can you give me `steps to reproduce` so I could take a look?

**Comment by lukas-a-brand** [comment]
@DreaMinder sure.

Package - Dep:
"nuxt": "^2.13.3",
"@nuxtjs/pwa": "^3.0.0-beta.20",
"nuxt-netlify-cache": "^1.0.2",

Package - Scripts:
    "build": "NUXT_TARGET='server' nuxt build --modern=server --no-lock",
    "build:static": "NUXT_TARGET='static' nuxt build --modern=server --no-lock",
    "export": "NUXT_TARGET='static' nuxt export",
    "generate": "yarn run build:static && yarn run export",
    "generate:cached": "NUXT_TARGET='static' nuxt-netlify-cache",


nuxt.config:

buildModules: [
      [
        '@nuxtjs/pwa',
      ]
    ],


Netlify Build command when called from hook ->  generate:cached

**Comment by DreaMinder** [comment]
@bstrdChronicles I haven't been able to reproduce any issues with PWA module. You didn't mention what exactly goes wrong in your case, but if sw.js was missing, it's probably not caused by this module, because Nuxt will treat /static/sw.js the same way as /static/favicon.ico, there shouldn't be any special logic... 

Here is my test-project I used for testing (both locally and on netlify): https://wonderful-mahavira-4f63e0.netlify.app/sw.js

Maybe it has something to do with bunch of command-flags in your commands? This module only runs `nuxt build && nuxt export`, you can't add flags there.

**Comment by lukas-a-brand** [comment]
> @bstrdChronicles I haven't been able to reproduce any issues with PWA module. You didn't mention what exactly goes wrong in your case, but if sw.js was missing, it's probably not caused by this module, because Nuxt will treat /static/sw.js the same way as /static/favicon.ico, there shouldn't be any special logic...
> 
> Here is my test-project I used for testing (both locally and on netlify): https://wonderful-mahavira-4f63e0.netlify.app/sw.js
> 
> Maybe it has something to do with bunch of command-flags in your commands? This module only runs `nuxt build && nuxt export`, you can't add flags there.

But the flags/env variables given to the nuxt-netlify-cache command are still accessible in the commands you run through that as far as I understood - so It cant really be that.

I will give you a deployed example soonish - I will be back haha :) ( Thanks for the help in the meantime )

**Comment by DreaMinder** [comment]
Hey, just letting you know that you can use cached builds without this module, maybe native implementation will work better for you: https://nuxtjs.org/blog/nuxt-static-improvements

**Comment by lukas-a-brand** [comment]
Hey, just saw the new release. will try it out. 
Thanks for your help. :)
